name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-vrmkit:
    name: Test VRMKit
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Test VRMKit
        run: make test-vrmkit

  test-vrmscenekit:
    name: Test VRMSceneKit
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.3
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
      - name: Test VRMSceneKit
        run: make test-vrmscenekit
